#Revisão PLN

Conteúdo:

*   **Tratamento de Texto:** Código feito em aula, mostrando limpeza do texto, tokenização e criação de bag of words
*   **Técnicas de Processamento de Texto:** Algoritmos independentes mostrando as etapas do processamento de texto, incluindo:
        1.   Pré-processamento
        2.   Remoção de Stopwords
        3.   Tokenização
        4.   One-Hot Encoding
        5.   Vectorizer
        6.   Stemming
        7.   Lemmatization
*   **Algoritmos de Treinamento:** Modelos de algoritmos de treinamento
        1.   Rede Neural [Keras]
        2.   LSTM
*   **Exercícios:** Exercícios 1 a 4 (tarefas relacionadas com processamento de texto). Cada exercício está dividido numa seção





__________________________________________________





##Tratamento de Texto

In [45]:
corpus = """rato roeu a roupa do rei de Roma,
O rato roeu a roupa do rei da Rússia,
O rato roeu a roupa do RodovaIho...
O rato a roer roía
E a rosa Rita Ramalho do rato a roer se ria.
O rato roeu a roupa do rei de roma
a rainha com raiva roeu o resto."""

# Pré-processamento
corpus_lower = corpus.lower()
trans_table = str.maketrans('.,\n', '   ')
corpus_limpo = corpus_lower.translate(trans_table)

# Criando as tokens a partir do Texto
tokens = corpus_limpo.split(" ")

# Removendo os stop words
stop_words = ['a', 'o', 'da', 'do', 'e', 'que', 'com', 'se', 'de']

tokens_limpos = []
for token in tokens:
    if token != '' and token not in stop_words:
        tokens_limpos.append( token )
print("Tokens: ", tokens_limpos, "\n")

# Criando o Bag Of Words com contagem de palavras
vocabulario = list(set(tokens_limpos))
print("Vocabulario: ", vocabulario, "\n")

bag_of_words = {}
for token in tokens_limpos:
    if token in bag_of_words:
        bag_of_words[token] = bag_of_words[token] + 1
    else:
        bag_of_words[token] = 1
print("Bag of Words (com contagem): ", bag_of_words)

Tokens:  ['rato', 'roeu', 'roupa', 'rei', 'roma', 'rato', 'roeu', 'roupa', 'rei', 'rússia', 'rato', 'roeu', 'roupa', 'rodovaiho', 'rato', 'roer', 'roía', 'rosa', 'rita', 'ramalho', 'rato', 'roer', 'ria', 'rato', 'roeu', 'roupa', 'rei', 'roma', 'rainha', 'raiva', 'roeu', 'resto'] 

Vocabulario:  ['rato', 'rússia', 'resto', 'rei', 'roía', 'roupa', 'rainha', 'rosa', 'raiva', 'rodovaiho', 'ramalho', 'roeu', 'roer', 'ria', 'rita', 'roma'] 

Bag of Words (com contagem):  {'rato': 6, 'roeu': 5, 'roupa': 4, 'rei': 3, 'roma': 2, 'rússia': 1, 'rodovaiho': 1, 'roer': 2, 'roía': 1, 'rosa': 1, 'rita': 1, 'ramalho': 1, 'ria': 1, 'rainha': 1, 'raiva': 1, 'resto': 1}


##Técnicas de Processamento de Texto

###Pré-processamento de Texto


Realiza o pré-processamento de texto, incluindo:
    <br> - Conversão para minúsculas
    <br> - Remoção de acentuação
    <br> - Remoção de pontuação
    <br> - Normalização de espaços

In [ ]:
import re
from unidecode import unidecode

def preprocess_text(text):
    # Converte para minúsculas
    text = text.lower()

    # Remove acentuação
    text = unidecode(text)

    # Remove pontuação
    text = re.sub(r'[^\w\s]', '', text)

    # Remove espaços extras
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Exemplo de uso
texto_exemplo = "Olá, Mundo! Eu tenho 42 maçãs. 😊"
print(preprocess_text(texto_exemplo))

ola mundo eu tenho 42 macas


###Remoção de Stopwords


Stopwords são palavras que não agregam sentido, como artigos, preposições, conjunções, pronomes e etc.

In [ ]:
import nltk
from nltk.corpus import stopwords

# Certifique-se de baixar as stopwords antes: nltk.download('stopwords')
nltk.download('stopwords')

def remover_stopwords(texto):
    # Obtemos a lista de stopwords para o idioma desejado (português neste caso).
    stop_words = set(stopwords.words('portuguese'))

    # Dividimos o texto em uma lista de palavras.
    palavras = texto.split()

    # Retornamos apenas as palavras que não estão na lista de stopwords.
    return " ".join([palavra for palavra in palavras if palavra not in stop_words])

# Exemplo de uso
texto_exemplo = "Este é um exemplo de texto com algumas palavras irrelevantes."
print(remover_stopwords(texto_exemplo))


Este exemplo texto algumas palavras irrelevantes.


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


###Tokenização [Tokenizer]

Tokenização é o processo de dividir um texto em palavras individuais (tokens). Neste exemplo, a função word_tokenize do NLTK  transforma o texto em uma lista de palavras, facilitando o processamento subsequente.

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

# Download the necessary data for tokenization
nltk.download('punkt_tab')

def tokenizar_texto(texto):
    return word_tokenize(texto)

# Exemplo de uso
texto_exemplo = "Este é um exemplo de tokenização."
print(tokenizar_texto(texto_exemplo))

# Iteração sobre os tokens
tokens = tokenizar_texto(texto_exemplo)
for i, token in enumerate(tokens, start=1):
    print(f"Token {i}: {token}")

['Este', 'é', 'um', 'exemplo', 'de', 'tokenização', '.']
Token 1: Este
Token 2: é
Token 3: um
Token 4: exemplo
Token 5: de
Token 6: tokenização
Token 7: .


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


###One-Hot Encoding

Transforma palavras únicas em vetores binários. Cada palavra é representada por um vetor onde somente uma posição é "1", indicando a presença daquela palavra. Isso é útil para algoritmos que não conseguem processar texto diretamente.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

def one_hot_encoding(lista_de_palavras):
    encoder = OneHotEncoder(sparse_output=False)
    # Convertemos a lista de palavras em um formato adequado para o encoder.
    palavras_transformadas = [[palavra] for palavra in lista_de_palavras]
    return encoder.fit_transform(palavras_transformadas)

# Exemplo de uso
texto_exemplo = "cachorro gato gato cachorro peixe"
tokens = texto_exemplo.split()
one_hot = one_hot_encoding(tokens)
print(one_hot)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


###Vetorização [Vectorizer - Bag of Words]

Bag of Words cria uma matriz onde cada linha representa um texto e cada coluna, uma palavra única do vocabulário. Os valores indicam o número de vezes que uma palavra aparece no texto.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

def bag_of_words(textos):
    vectorizer = CountVectorizer()
    # Ajusta o vetorizador ao texto e transforma.
    matriz = vectorizer.fit_transform(textos)
    return matriz.toarray(), vectorizer.get_feature_names_out()

# Exemplo de uso
textos_exemplo = ["cachorro gato peixe", "gato peixe", "cachorro cachorro gato"]
matriz, palavras = bag_of_words(textos_exemplo)
print("Matriz:\n", matriz)
print("Palavras:\n", palavras)


Matriz:
 [[1 1 1]
 [0 1 1]
 [2 1 0]]
Palavras:
 ['cachorro' 'gato' 'peixe']


### Normatização - Stemming


O stemming reduz as palavras à sua forma básica (radical). É útil para considerar diferentes formas gramaticais como equivalentes (ex.: "correr", "corremos").

In [ ]:
from nltk.stem import RSLPStemmer

nltk.download('rslp')

def aplicar_stemming(texto):
    stemmer = RSLPStemmer()  # Stemmer específico para o português.
    palavras = texto.split()  # Dividimos o texto em palavras.
    # Aplicamos o stemming em cada palavra.
    return " ".join([stemmer.stem(palavra) for palavra in palavras])

# Exemplo de uso
texto_exemplo = "corremos correrá correndo corredores"
print(aplicar_stemming(texto_exemplo))


corr corr corr corr


[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Unzipping stemmers/rslp.zip.


### Normatização - Lemmatization


A lematização é semelhante ao stemming, mas mais precisa. Enquanto o stemming corta palavras para obter o radical, a lematização considera o contexto para obter a forma base correta.

In [38]:
import spacy

# Certifique-se de instalar o modelo: python -m spacy download pt_core_news_sm
nlp = spacy.load("pt_core_news_sm")

def aplicar_lemmatizacao(texto):
    doc = nlp(texto)  # Processamos o texto com Spacy.
    # Retornamos os lemas de cada token.
    return " ".join([token.lemma_ for token in doc])

# Exemplo de uso
texto_exemplo = "Os meninos correram para pegar o trem."
print(aplicar_lemmatizacao(texto_exemplo))


o menino correr para pegar ele tr .


##Algoritmos de Treinamento

###Rede Neural [Keras] - Classificação de Texto

Classifica textos em diferentes categorias (por exemplo, sentimento positivo ou negativo).

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

# Exemplo de dados de texto
textos = ["Eu amo este produto", "Muito ruim, não gostei", "Excelente, recomendo", "Horrível, não vale a pena", "Produto maravilhoso"]
labels = [1, 0, 1, 0, 1]  # 1 = positivo, 0 = negativo

# Tokenização do texto
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(textos)
X = tokenizer.texts_to_sequences(textos)

# Padding para que todas as sequências tenham o mesmo tamanho
X_pad = pad_sequences(X, padding='post')

# Criar o modelo
modelo = Sequential([
    Embedding(input_dim=10000, output_dim=64, input_length=X_pad.shape[1]),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')  # Saída binária (positivo ou negativo)
])

modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Treinar o modelo
modelo.fit(X_pad, np.array(labels), epochs=10)

# Avaliar o modelo
print(modelo.evaluate(X_pad, np.array(labels)))

###LSTM - Classificação de Texto

Ótimo para processar sequências de texto, como análises de sentimentos ou predição de tópicos, permitindo que o modelo lembre de informações anteriores da sequência.

In [ ]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding, Dropout
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

# Exemplo de dados de texto
textos = ["Eu adoro programação", "Detesto erros de código", "Muito fácil de aprender", "Erros são frustrantes", "Aprender programação é divertido"]
labels = [1, 0, 1, 0, 1]  # 1 = positivo, 0 = negativo

# Tokenização do texto
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(textos)
X = tokenizer.texts_to_sequences(textos)

# Padding para que todas as sequências tenham o mesmo tamanho
X_pad = pad_sequences(X, padding='post')

# Criar o modelo LSTM
modelo = Sequential([
    Embedding(input_dim=10000, output_dim=64, input_length=X_pad.shape[1]),
    LSTM(128),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')  # Saída binária (positivo ou negativo)
])

modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Treinar o modelo
modelo.fit(X_pad, np.array(labels), epochs=10)

# Avaliar o modelo
print(modelo.evaluate(X_pad, np.array(labels)))

##Exercícios

###Exercício 1

Com base no texto, faça um código para extrair o texto que está entre
o primeiro (.) e a primeira (,). Utilize a função find para localizar
as posições do ponto e da virgula no texto e, em seguida, faça um laço
for para gerar um texto novo com os caracteres entre o ponto e a virgula

In [39]:
texto = "Python é uma linguagem de programação poderosa e versátil.\
        É amplamente utilizada em desenvolvimento web, ciência de\
        dados, inteligência artificial e muito mais."

# Encontrar o ponto
posicao_ponto = texto.find(".")

# Definir a primeira vírgula após o ponto
# obs: posicao_ponto serve como argumento para estabelcer o início da busca
posicao_virgula = texto.find(",", posicao_ponto)

# Necessário inicializar a variável antes do laço como string vazia
novo_texto = ""

# Laço for para gerar o novo texto
for i in range(posicao_ponto + 1, posicao_virgula):
    novo_texto += texto[i]

# Remover caracteres em branco no início (lstrip, à esquerda) e final (rstrip, à direita)
novo_texto = novo_texto.lstrip().rstrip()

print(f"Texto extraído: '{novo_texto}'")

Texto extraído: 'É amplamente utilizada em desenvolvimento web'


###Exercício 2

1) Crie uma lista de dicionários para armazenar comentários e emoções conforme a tabela <br>
2) Faça uma rotina para totalizar a quantidade de comentários negativos e comentários positivos <br>
3) Calcule e mostre na tela a proporção de cada sentimento em relação ao total de comentários <br>
4) Faça uma rotina para mostrar apenas os comentários positivos <br>
5) Adicione uma chave em cada dicionário chamado sentimento_valor que conterá 0 se o sentimento for negativo ou 1 se o sentimento for positivo

In [40]:
# Inicializar variáveis
total_comentarios = 0
comentarios_positivos = 0
comentarios_negativos = 0

# Criar lista de dicionários
dicionarios = [
    { "autor": "João", "comentario": "Estou tão feliz hoje!", "sentimento_valor": 1 },
    { "autor": "Maria", "comentario": "Este filme é tão triste.", "sentimento_valor": 0 },
    { "autor": "Carlos", "comentario": "Que dia chuvoso entediante...", "sentimento_valor": 0 },
    { "autor": "Ana", "comentario": "Adorei a nova música da banda!", "sentimento_valor": 1 },
    { "autor": "Roberto", "comentario": "Eureka, consegui resolver este problema", "sentimento_valor": 1 }
]

# Totalizar comentários
for comentario in dicionarios:
    total_comentarios += 1
print(f"Há {total_comentarios} comentários ao todo.\n")

# Exibir comentários positivos
print("Comentários Positivos:")

for comentario in dicionarios:
    if comentario["sentimento_valor"] == 1:
        print(f"{comentario['autor']}: {comentario['comentario']}")
        # Contabilizar comentários positivos
        comentarios_positivos += 1
# Definir proporção de comentários positivos
proporcao_positivos = (comentarios_positivos / total_comentarios) *100
print(f"Há {comentarios_positivos} comentário(s) positivo(s), representado {proporcao_positivos}% do total de comentários.\n")

# Exibir comentários negativos
print("Comentários Negativos:")

for comentario in dicionarios:
    if comentario["sentimento_valor"] == 0:
        print(f"{comentario['autor']}: {comentario['comentario']}")
        # Contabilizar comentários negativos
        comentarios_negativos += 1
# Definir proporção de comentários negativos
proporcao_negativos = (comentarios_negativos / total_comentarios) *100
print(f"Há {comentarios_negativos} comentário(s) negativo(s), representado {proporcao_negativos}% do total de comentários.\n")

Há 5 comentários ao todo.

Comentários Positivos:
João: Estou tão feliz hoje!
Ana: Adorei a nova música da banda!
Roberto: Eureka, consegui resolver este problema
Há 3 comentário(s) positivo(s), representado 60.0% do total de comentários.

Comentários Negativos:
Maria: Este filme é tão triste.
Carlos: Que dia chuvoso entediante...
Há 2 comentário(s) negativo(s), representado 40.0% do total de comentários.



###Exercício 3

Contexto: Você foi contratado por uma empresa de marketing digital para analisar comentários de clientes em uma rede social. Para começar a análise, é necessário limpar os dados e deixá-los em um formato adequado para a aplicação de algoritmos de NLP.

Tarefa: Crie uma função que...
<br> 1) Converta todas as palavras para minúsculas.
<br> 2) Elimine caracteres especiais (pontuação, emojis, etc.).
<br> 3) Retorne uma lista com as palavras pré-processadas

Exemplo de parâmetro: "Adorei o produto! Super recomendo 😍"
Exemplo de retorno: ["adorei", "o", "produto", "super", "recomendo"]

In [41]:
import re

# Criar função
def preprocessar_comentario(comentario):
    # Converter as palavras em minúsculas
    comentario = comentario.lower()

    # Eliminar caracteres especiais (pontuação, emojis, etc.), utilizando regex
    comentario = re.sub(r'[^\w\s]', '', comentario)  # Remove pontuação
    comentario = re.sub(r'\d+', '', comentario)  # Remove números (se necessário)

    # Separar o comentário em palavras
    palavras = comentario.split()

    # Retornar lista de palavras pré-processadas
    return palavras

# Uso com comentário passado como parâmetro
exemplo = "Adorei o produto! Super recomendo 😍"
resultado = preprocessar_comentario(exemplo)
print(f"Exemplo: Adorei o produto! Super recomendo 😍  -> Resultado: {resultado}\n")

# Uso com entrada do usuário
comentario_usuario = input("Digite um comentário: ")
resultado = preprocessar_comentario(comentario_usuario)
print(f"Comentário pré-processado: {resultado}")

Exemplo: Adorei o produto! Super recomendo 😍  -> Resultado: ['adorei', 'o', 'produto', 'super', 'recomendo']

Digite um comentário: Olá, como vai você, hein?!
Comentário pré-processado: ['olá', 'como', 'vai', 'você', 'hein']


###Exercício 4

Contexto: Você trabalha em uma startup que oferece suporte via mensagens de texto. As mensagens dos clientes são escritas de maneira informal, com abreviações e erros de digitação. Sua tarefa é normalizar esses textos para facilitar a análise.

Tarefa:
<br> 1) Identifique e corrija abreviações e erros comuns (por exemplo, "vc" → "você", "eh" → "é").
<br> 2) Remova gírias e expressões que não adicionam valor semântico.
<br> 3) Retorne o texto normalizado.

Exemplo de entrada: "Vc eh mt bom, recomendo mto!!!"
Exemplo de saída: "você é muito bom recomendo muito"

Dica: Construa um dicionário para de gírias de maneira que a chave seja a gíria e o valor a palavra formal.

In [42]:
import re

# Dicionário de gírias
girias = { "mto": "muito", "mt": "muito", "vc": "você", "eh": "é" }
"""
    Como há duas chaves com valores iguais, é necessário manter
    a chave mais longa primeiro para não afetar a saída e
    duplicar caracteres no momento da substituição
"""

comentario = "Vc eh mt bom, recomendo mto!!!"

# Transformar o texto em minúsculo
comentario = comentario.lower()

# Eliminar gírias e expressões que não adicionam valor semântico
comentario = re.sub(r'[^\w\s]', '', comentario)  # Remove pontuação
comentario = re.sub(r'\d+', '', comentario)  # Remove números (se necessário)

# Substituir as chaves (abreviações) do dicionário pelos seus valores (correções)
for abreviacao, correcao in girias.items():
    comentario = comentario.replace(abreviacao, correcao)

# Remover espaços extras
comentario = ' '.join(comentario.split())

print(f"Comentário corrigido: '{comentario}'")

Comentário corrigido: 'você é muito bom recomendo muito'
